### ISSUE TITLE
Not getting very far...

### ISSUE THREAD

**Issue by rbnpi** [josephburnett/sonic-jam#1]
Hi
I've downloaded the system, run the osx file and got the web-browser window showing.
However all I can expand on the screen is the top elipses which gives
{bpc: widgh: +/- }
and underneath
[- 1 2 3 8 16]

How do I get further?

terminal gives

rbn-imac-new:~ rbn$ /Users/rbn/Downloads/sonic-jam-osx ; exit;
2016/07/02 13:46:58 Starting OSC server.
2016/07/02 13:46:58 Starting websocket server.
2016/07/02 13:46:58 Starting the UI webserver.
2016/07/02 13:47:12 Connected client: bMIAopTnhlFHVqFp

I have SP2.11dev running

**Comment by rbnpi** [comment]
Further to this, I've switched to SP2.10 Same dresult. However I notice errors in the SP serverlog
```
OSC handler exception for address: /ping
Unknown arg type to encode: nil
["/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:99:in `block in encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `each'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_client.rb:32:in `send'", "/Applications/Sonic Pi.app/Contents/MacOS/../../app/server/bin/sonic-pi-server.rb:216:in `block in <main>'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:92:in `block in start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `loop'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:36:in `block in initialize'"]
OSC handler exception for address: /ping
Unknown arg type to encode: nil
["/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:99:in `block in encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `each'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_client.rb:32:in `send'", "/Applications/Sonic Pi.app/Contents/MacOS/../../app/server/bin/sonic-pi-server.rb:216:in `block in <main>'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:92:in `block in start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `loop'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:36:in `block in initialize'"]
OSC handler exception for address: /ping
Unknown arg type to encode: nil
["/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:99:in `block in encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `each'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_client.rb:32:in `send'", "/Applications/Sonic Pi.app/Contents/MacOS/../../app/server/bin/sonic-pi-server.rb:216:in `block in <main>'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:92:in `block in start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `loop'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:36:in `block in initialize'"]
OSC handler exception for address: /ping
Unknown arg type to encode: nil
["/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:99:in `block in encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `each'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_client.rb:32:in `send'", "/Applications/Sonic Pi.app/Contents/MacOS/../../app/server/bin/sonic-pi-server.rb:216:in `block in <main>'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:92:in `block in start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `loop'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:36:in `block in initialize'"]
OSC handler exception for address: /ping
Unknown arg type to encode: nil
["/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:99:in `block in encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `each'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_client.rb:32:in `send'", "/Applications/Sonic Pi.app/Contents/MacOS/../../app/server/bin/sonic-pi-server.rb:216:in `block in <main>'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:92:in `block in start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `loop'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:36:in `block in initialize'"]
OSC handler exception for address: /ping
Unknown arg type to encode: nil
["/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:99:in `block in encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `each'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_client.rb:32:in `send'", "/Applications/Sonic Pi.app/Contents/MacOS/../../app/server/bin/sonic-pi-server.rb:216:in `block in <main>'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:92:in `block in start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `loop'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:36:in `block in initialize'"]
OSC handler exception for address: /ping
Unknown arg type to encode: nil
["/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:99:in `block in encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `each'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_client.rb:32:in `send'", "/Applications/Sonic Pi.app/Contents/MacOS/../../app/server/bin/sonic-pi-server.rb:216:in `block in <main>'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:92:in `block in start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `loop'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:36:in `block in initialize'"]
OSC handler exception for address: /ping
Unknown arg type to encode: nil
["/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:99:in `block in encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `each'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_client.rb:32:in `send'", "/Applications/Sonic Pi.app/Contents/MacOS/../../app/server/bin/sonic-pi-server.rb:216:in `block in <main>'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:92:in `block in start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `loop'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:36:in `block in initialize'"]
OSC handler exception for address: /ping
Unknown arg type to encode: nil
["/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:99:in `block in encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `each'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_client.rb:32:in `send'", "/Applications/Sonic Pi.app/Contents/MacOS/../../app/server/bin/sonic-pi-server.rb:216:in `block in <main>'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:92:in `block in start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `loop'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:36:in `block in initialize'"]
OSC handler exception for address: /ping
Unknown arg type to encode: nil
["/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:99:in `block in encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `each'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/oscencode.rb:54:in `encode_single_message'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_client.rb:32:in `send'", "/Applications/Sonic Pi.app/Contents/MacOS/../../app/server/bin/sonic-pi-server.rb:216:in `block in <main>'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:92:in `block in start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `loop'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:73:in `start_listener'", "/Applications/Sonic Pi.app/app/server/sonicpi/lib/sonicpi/osc/udp_server.rb:36:in `block in initialize'"]
 ```

**Comment by josephburnett** [comment]
What version of Sonic Pi are you using?

**Comment by rbnpi** [comment]
2.10 (I switched from 2.11dev)

**Comment by rbnpi** [comment]
I've now tried it with SP 2.9 and it is OK there. So something seems to have changed in 2.10 the latest release version which breaks it.

**Comment by rbnpi** [comment]
I get further with 2.9: root shows on gui, can expand a track and get selection for synth or sample, but don't get list of either to choose from.

**Comment by josephburnett** [comment]
I tried with SP 2.10 on a vanilla Macbook Air and it works.

After you select "synth" or "sample", press the Enter button.  It should turn grey and then show a dropdown to select the specific synth or sample.  Does that work?

**Comment by josephburnett** [comment]
Hey Robin, see if it will work now.  I've added a few sample tracks so you can see right away if it's working.  You'll see the cursor sweeping across the grid of zeros.  (I updated the binaries too, so you can use one of the prebuilt ones: https://github.com/josephburnett/sonic-jam#quick-start)
