### ISSUE TITLE
Debug flag causes panic

### ISSUE THREAD

**Issue by josephburnett** [josephburnett/sonic-jam#28]
joseph@joseph-macbookpro:~/sonic-jam$ ./build/sonic-jam -debug
2016/07/17 23:12:24 Starting OSC server.
2016/07/17 23:12:24 Starting websocket server on 127.0.0.1:4550
2016/07/17 23:12:24 Received from server: /errors,s ["*","[\"Connection refused - send(2)\",\"/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/osc/udp_client.rb:33:in `send'\",\"/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/osc/udp_client.rb:33:in `send'\",\"eval:33:in `block (2 levels) in __spider_eval'\",\"/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/lang/core.rb:755:in `block in live_loop'\",\"/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/lang/core.rb:777:in `block (3 levels) in live_loop'\",\"/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/lang/core.rb:824:in `block_duration'\",\"/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/lang/core.rb:861:in `block_slept?'\",\"/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/lang/core.rb:774:in `block (2 levels) in live_loop'\",\"/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/lang/core.rb:773:in `loop'\",\"/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/lang/core.rb:773:in `block in live_loop'\",\"/usr/lib/sonic-pi/server/sonicpi/lib/sonicpi/lang/core.rb:2622:in `block in in_thread'\"]"]
panic: runtime error: index out of range

goroutine 7 [running]:
panic(0x7f2f40, 0xc82000e0d0)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
vendor/github.com/scgolang/osc.(*Message).ReadString(0xc820014b90, 0x0, 0x0, 0x0, 0x0)
	/home/joseph/sonic-jam/osc-bridge/src/vendor/github.com/scgolang/osc/message.go:91 +0x4e5
sonicjam/bridge.oscHandler(0xc820014b90, 0x0, 0x0)
	/home/joseph/sonic-jam/osc-bridge/src/sonicjam/bridge/bridge.go:170 +0x275
vendor/github.com/scgolang/osc.Dispatcher.DispatchMessage(0xc8200fa0f0, 0xc820014b90, 0x0, 0x0)
	/home/joseph/sonic-jam/osc-bridge/src/vendor/github.com/scgolang/osc/dispatcher.go:24 +0x113
created by vendor/github.com/scgolang/osc.(*UDPConn).serve
	/home/joseph/sonic-jam/osc-bridge/src/vendor/github.com/scgolang/osc/udp.go:78 +0x2cc

**Comment by josephburnett** [comment]
@0b0b26daf146f7e8c94a0cf01f6ead92a5dd1358

Disable debug of OSC messages bound for client.
